.if n .ds Q \&"
.if t .ds Q ``
.if n .ds U \&"
.if t .ds U ''
.TH "backup" 8 
.tr \&
.nr bi 0
.nr ll 0
.nr el 0
.de DS
..
.de DE
..
.de Pp
.ie \\n(ll>0 \{\
.ie \\n(bi=1 \{\
.nr bi 0
.if \\n(t\\n(ll=0 \{.IP \\(bu\}
.if \\n(t\\n(ll=1 \{.IP \\n+(e\\n(el.\}
.\}
.el .sp 
.\}
.el \{\
.ie \\nh=1 \{\
.LP
.nr h 0
.\}
.el .PP 
.\}
..
.SH NAME  

.Pp
backup - Volume by volume backup of the Coda File System
.Pp
.Pp
.Pp
.SH SYNOPSIS

.Pp
\fBbackup\fP [-p poll_period] [-t timeout] <dumplist> [dumpdir]
.Pp
.Pp
.Pp
.SH DESCRIPTION

.Pp
\fBbackup\fP performs the clone and dump phases of the Coda backup mechanism.
\fIdumplist\fP is a file as described in \fIdumplist\fP(5).  It also
reads \fIvicetab\fP which is described in \fIvicetab\fP(5) to know
where to place dump files.
.Pp
The backup program creates many lines of information as the phases progress. It
is a good idea to redirect standard output to a log file. A sample of this log file  \fIbackuplogs\fP(5).  After both phases are completed, it prints out a list of volumes in several groupings, and some histograms detailing size and speed of the dumpfiles transferred. The first group are the volumes that were successfully backed up on all servers in their VSG. The second group contains volumes that were successful on some, but not
all of their VSGs. The third group contains volumes that were complete failures.
The last group contains volumes that are in the VLDB or VRDB but not in the
\fIdumplist\fP\&.
.Pp
The second and third groups use an n-letter word to describe the last successful
operation that succeeded on each replica. The kth position in the n-letter word
corresponds to the kth replica in the VRDB entry for this volume. One of four
letters appears in each position: \&"L\&", \&"C\&", \&"D\&", and \&"M\&".
\&"L\&" means the replica was only locked, \&"C\&" means it was cloned but
not dumped, \&"D\&" means it was dumped (but not marked as such on the server,
see the discusion in the manual chapter on backup), and \&"M\&" means all phases
completed successfully. 
.Pp
\fBbackup\fP supports the following command line options:
.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fB-p\fP \fIpoll_period\fP"
.nr bi 1
.Pp
Number of seconds to
sleep between polls a servers that \fBbackup\fP thinks are down.
.Pp
.if \n(ll>1 .RE
.nr ll -1
.Pp
.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fB-t\fP \fItimeout\fP"
.nr bi 1
.Pp
Timout value, in seconds, for RPC2 calls.
.Pp
.if \n(ll>1 .RE
.nr ll -1
.Pp
.Pp
.SH SEE ALSO

.Pp
volutil (8), dumplist (5), backuplogs (5), Backup chapter of the Coda Manual.
.Pp
.Pp
.SH AUTHOR

.Pp
David C. Steere, 1991, Created
updated 1998, -hmp
.Pp
