.if n .ds Q \&"
.if t .ds Q ``
.if n .ds U \&"
.if t .ds U ''
.TH "dumplist" 5 
.tr \&
.nr bi 0
.nr ll 0
.nr el 0
.de DS
..
.de DE
..
.de Pp
.ie \\n(ll>0 \{\
.ie \\n(bi=1 \{\
.nr bi 0
.if \\n(t\\n(ll=0 \{.IP \\(bu\}
.if \\n(t\\n(ll=1 \{.IP \\n+(e\\n(el.\}
.\}
.el .sp 
.\}
.el \{\
.ie \\nh=1 \{\
.LP
.nr h 0
.\}
.el .PP 
.\}
..
.SH NAME  

.Pp
dumplist - List of volumes to be archived by the Coda backup mechanism
.Pp
.Pp
.Pp
.SH DESCRIPTION

.Pp
The dumplist file contains information for the \fBbackup\fP(8) program. It consists of a list of volumes to be archived. 
.Pp
Each entry in the list
contains three tab separated fields: the volumeId (groupId), the schedule for full
and incremental dumps, and a comment used to facilitate reading the output of the
\fBbackup\fP program. The schedule contains a number of \&"F\&" and \&"I\&" characters. Each
character represents what form of dump to take for that day in the schedule. The length
of the period is the number of characters in the schedule. For instance, \&"FIIIIII\&"
means take one full dump followed by 6 incrementals, whereas \&"F\&" means take a full
dump every day. For convenience, the first character in a 7 day schedule refers to Sunday.
.Pp
.Pp
.Pp
.SH EXAMPLE

.Pp
The following does a full backup of \fIcoda_root\fP, \fIcoda_root.i386\fP, and
\fIcoda_root.tmp\fP on Monday while it does a full backup of
\fIcoda_root.project\fP and \fIcoda_root.usr\fP on Wednesday.  It uses
\fI/vicepa/backup\fP and \fI/usr/codabackup/backup\fP to store the dump files.
.DS
.sp 
.ft RR
.nf
7F000000        IFIIIII         coda_root
7F000001        IFIIIII         coda_root.i386
7F000002        IIIFIII         coda_root.project
7F000003        IFIIIII         coda_root.tmp
7F000004        IIIFIII         coda_root.usr
7F000005        IFIIIII         coda_root.misc
.DE
.fi 
.ec
.ft P
.sp
.Pp
.Pp
.SH NOTES

.Pp
In prior release of coda, the key words \&"Partition\&" and \&"Volumes\&" were
used to distinguish between seperate sections of the dump file needed
by \f(CRbackup\fP\&.  \f(CRdumplist\fP should now only include the
Volume backup information and does not need the key word Volume.  Nor
is the keyword Partitions needed any more as \f(CRbackup\fP reads
vicetab for backup partition information.
.Pp
.SH SEE ALSO

.Pp
backup (8), creatvol (8), createvol_rep (8), vicetab (5)
.Pp
.Pp
.SH AUTHOR

.Pp
David C. Steere, 1991, Created
updated 1998, hmp
.Pp
