if get_option('install-dev')
  install_headers([
    'rpc2/codatunnel.h',
    'rpc2/errors.h',
    'rpc2/multi.h',
    'rpc2/pack_helper.h',
    'rpc2/rpc2.h',
    'rpc2/rpc2_addrinfo.h',
    'rpc2/se.h',
    'rpc2/secure.h',
    'rpc2/sftp.h',
    'rpc2/tcpftp.h',
  ], subdir : 'rpc2')
endif

rpc2_inc = include_directories('.')
