image: registry.cmusatyalab.org/coda/coda-packaging/coda-build-src

# should be a no-op if the submitter used the pre-commit hooks
pre_commit:
  stage: .pre
  variables:
    PREK_HOME: ${CI_PROJECT_DIR}/.cache/prek
  cache:
    key: precommit
    paths:
      - $PREK_HOME
  script:
    - prek run -v --all-files
    - tools/version_check.sh

distbuild:
  stage: build
  variables:
    CCACHE_DIR: ${CI_PROJECT_DIR}/.cache/ccache
    CCACHE_BASEDIR: ${CI_PROJECT_DIR}
    CCACHE_COMPILERCHECK: content
    CCACHE_NOHASHDIR: "true"
    CCACHE_MAXSIZE: 500M
    MESON_PACKAGE_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/wrapdb
  cache:
    key: default
    paths:
      - $CCACHE_DIR
      - $MESON_PACKAGE_CACHE_DIR
  before_script:
    - meson setup build --prefix=/usr
  script:
    - meson dist -C build
  artifacts:
    expire_in: 1 week
    paths:
      - build/meson-dist/coda-*.tar.xz
      - build/meson-dist/coda-*.tar.xz.sha256sum
  only:
    - master
    - tags
    - /^coda-.*$/

testbuild:
  extends: distbuild
  only: null
  except:
    - master
    - tags
    - /^coda-.*$/

pages:
  extends: distbuild
  stage: deploy
  variables:
    MKDOCS_CACHE: ${CI_PROJECT_DIR}/.cache/plugins
  cache:
    key: docs
    paths:
      - $MKDOCS_CACHE
  script:
    - meson compile docs -C build
    - mv build/site public
    #- doxygen doxygen/Doxyfile
    #- mv doxygen/html/ public/doxygen
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
