sudo: false

language: c
cache: ccache

addons:
  apt:
    packages:
    - libreadline-dev
    - libncurses5-dev
    - liblua5.1-0-dev
    - flex
    - bison
    - pkg-config
    - python
    - automake
    - valgrind

before_script:
  - ./bootstrap.sh
  - ./configure --prefix=/usr --with-lua --without-libuv
script:
  - DISTCHECK_CONFIGURE_FLAGS=--without-libuv make -j2 distcheck
  - make -j2 check
  - make -j2 memcheck
