venus_inc = include_directories('.')

venus_sources = [
  '9pfs.cc',
  '9pfs.h',
  'SpookyV2.cc',
  'SpookyV2.h',
  'archive.c',
  'archive.h',
  'binding.cc',
  'binding.h',
  'comm.cc',
  'comm.h',
  'comm_daemon.cc',
  'daemon.cc',
  'fso.h',
  'fso0.cc',
  'fso1.cc',
  'fso_cachefile.cc',
  'fso_cachefile.h',
  'fso_cfscalls0.cc',
  'fso_cfscalls1.cc',
  'fso_cfscalls2.cc',
  'fso_daemon.cc',
  'fso_dir.cc',
  'hdb.cc',
  'hdb.h',
  'hdb_daemon.cc',
  'local.h',
  'local_cml.cc',
  'local_fake.cc',
  'local_fso.cc',
  'local_repair.cc',
  'local_vol.cc',
  'mariner.cc',
  'mariner.h',
  'mgrp.cc',
  'mgrp.h',
  'nt_util.cc',
  'nt_util.h',
  'realm.cc',
  'realm.h',
  'realmdb.cc',
  'realmdb.h',
  'rec_dllist.h',
  'refcounted.h',
  'sighand.cc',
  'sighand.h',
  'spool.cc',
  'tallyent.cc',
  'tallyent.h',
  'user.cc',
  'user.h',
  'venus.cc',
  'venus.private.h',
  'venuscb.cc',
  'venuscb.h',
  'venusfid.h',
  'venusrecov.cc',
  'venusrecov.h',
  'venusstats.h',
  'venusutil.cc',
  'venusvol.cc',
  'venusvol.h',
  'vol_COP2.cc',
  'vol_cml.cc',
  'vol_daemon.cc',
  'vol_reintegrate.cc',
  'vol_repair.cc',
  'vol_resolve.cc',
  'vol_vcb.cc',
  'vproc.cc',
  'vproc.h',
  'vproc_pathname.cc',
  'vproc_pioctl.cc',
  'vproc_vfscalls.cc',
  'vsg.cc',
  'vsg.h',
  'worker.cc',
  'worker.h',
]

venus_cpp_args = ['-DVENUS', '-DTIMING', '-DVENUSDEBUG']

if not get_option('build_client').disabled()
  executable('vutil',
    ['vutil.cc'],
    include_directories : [
      config_h_include,
      base_inc,
      kerndep_inc,
      util_inc,
      vicedep_inc,
      dir_inc,
      al_inc,
      auth2_inc,
      vv_inc,
      lka_inc,
      vol_inc,
      librepair_inc,
    ],
    dependencies : [rvm_rpc2_dep, base_dep],
    install : true,
    install_dir : get_option('sbindir'),
  )

  install_man('vutil.8')
endif

if not get_option('build_client').disabled()
  venus_env = environment()
  venus_env.append('CFLAGS', '-DVENUS')
  venus_env.append('CXXFLAGS', '-DVENUS')

  executable('venus',
    venus_sources,
    include_directories : [
      config_h_include,
      base_inc,
      kerndep_inc,
      util_inc,
      vicedep_inc,
      dir_inc,
      al_inc,
      auth2_inc,
      vv_inc,
      lka_inc,
      vol_inc,
      librepair_inc,
    ],
    cpp_args : venus_cpp_args,
    dependencies : [
      repio_dep, lka_dep, vv_dep, dir_dep, vicedep_dep,
      util_dep, base_dep, rwcdb_dep, rvm_rpc2_dep,
    ],
    link_with : [
      librepio_lib,
      lka_lib,
      vv_lib,
      dir_lib,
      venusdep_lib,
      util_lib,
      rwcdb_lib,
      base_lib,
    ],
    install : true,
    install_dir : get_option('sbindir'),
  )

  install_man('venus.8')

  install_data(
    ['realms', 'venus.conf.ex'],
    install_dir : sysconfdirx,
  )
endif
