util_sources = [
  'arrlist.cc',
  'arrlist.h',
  'bitmap.cc',
  'bitmap.h',
  'bitmap7.cc',
  'bitmap7.h',
  'bitvect.c',
  'bitvect.h',
  'bstree.cc',
  'bstree.h',
  'daemonizer.c',
  'daemonizer.h',
  'dhash.cc',
  'dhash.h',
  'dict.cc',
  'dict.h',
  'dlist.cc',
  'dlist.h',
  'getsecret.cc',
  'getsecret.h',
  'histo.c',
  'histo.h',
  'mkpath.c',
  'mkpath.h',
  'ohash.cc',
  'ohash.h',
  'olist.cc',
  'olist.h',
  'rec_bstree.cc',
  'rec_bstree.h',
  'rec_dhash.cc',
  'rec_dhash.h',
  'rec_dlist.cc',
  'rec_dlist.h',
  'rec_ohash.cc',
  'rec_ohash.h',
  'rec_olist.cc',
  'rec_olist.h',
  'rec_smolist.cc',
  'rec_smolist.h',
  'recvarl.cc',
  'recvarl.h',
  'rvmlib.c',
  'rvmlib.h',
  'rvmtesting.cc',
  'rvmtesting.h',
  'util.c',
  'util.h',
  'vice_file.c',
  'vice_file.h',
  'vmindex.cc',
  'vmindex.h',
]

util_lib = static_library('util',
  util_sources,
  build_by_default : false,
  include_directories : [config_h_include],
  dependencies : [base_dep, rpc2_dep, rvm_dep],
)

util_inc = include_directories('.')

util_dep = declare_dependency(
  include_directories : util_inc,
  link_with : util_lib,
)
