.\" COPYRIGHT NOTICE
.\" Copyright (c) 1994 Carnegie Mellon University
.\" All Rights Reserved.
.\" 
.\" See <cmu_copyright.h> for use and distribution information.
.\" 
.\" 
.\" HISTORY
.\" $Log: boolarg.3,v $
.\" Revision 1.1  1996/11/22 19:19:22  braam
.\" First Checkin (pre-release)
.\"
Revision 1.1  96/06/03  18:59:59  satya
Initial revision

.\" Revision 1.2  1995/10/18  14:57:46  moore
.\" 	Created libcs man(3) pages from mach entries
.\" 	[1995/10/18  14:52:41  moore]
.\"
.\" $EndLog$
.\" Copyright (c) 1990 Carnegie Mellon University
.\" All rights reserved.
.\" 
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted, provided that both the copyright
.\" notice and this permission notice appear in all copies of the
.\" software, derivative works or modified versions, and any portions
.\" thereof, and that both notices appear in supporting documentation.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND CARNEGIE MELLON UNIVERSITY
.\" DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT
.\" SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE FOR ANY SPECIAL, DIRECT,
.\" INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
.\" RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
.\" CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
.\" CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" Users of this software agree to return to Carnegie Mellon any
.\" improvements or extensions that they make and grant Carnegie the
.\" rights to redistribute these changes.
.\"
.\" Export of this software is permitted only after complying with the
.\" regulations of the U.S. Deptartment of Commerce relating to the
.\" Export of Technical Data.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" HISTORY
.\" $Log: boolarg.3,v $
.\" Revision 1.1  1996/11/22 19:19:22  braam
.\" First Checkin (pre-release)
.\"
Revision 1.1  96/06/03  18:59:59  satya
Initial revision

.\" Revision 1.2  1995/10/18  14:57:46  moore
.\" 	Created libcs man(3) pages from mach entries
.\" 	[1995/10/18  14:52:41  moore]
.\"
.\" Revision 1.1.1.2  1995/10/18  14:52:41  moore
.\" 	Created libcs man(3) pages from mach entries
.\"
.\" Revision 1.2  90/12/12  15:46:48  mja
.\" 	Add copyright/disclaimer for distribution.
.\" 
.\" 13-Nov-86  Andi Swimmer (andi) at Carnegie-Mellon University
.\" 	Revised for 4.3.
.\" 
.\" 20-Jun-86  David VanRyzin at Carnegie-Mellon University
.\" 	Updated manual entry for 4.2 conversion.  Error message now goes to stderr
.\" 	instead of stdout.
.\" 
.\" 05-Dec-79  Steven Shafer (sas) at Carnegie-Mellon University
.\" 	Created.
.\" 
.TH BOOLARG 3 6/20/86
.CM 4
.SH NAME
boolarg \- parse boolean argument or ask user
.SH SYNOPSIS
.B 
int boolarg (ptr,brk,prompt,defalt);
.br
.B
char **ptr,*brk,*prompt;
.br
.B
int defalt;
.SH DESCRIPTION
.I 
Boolarg
attempts to parse an argument from a string, passing
the string pointer
.I 
ptr
and the break character set
.I 
brk
to the
.IR nxtarg (3)
routine.
If there is an argument parsed, and it is a legal boolean,
then its value is returned by
.IR boolarg .
If there is no argument, or it is not valid, then an error
message is printed to stderr and the routine
.IR getbool (3)
is passed the remaining arguments.
The value of
.I 
getbool
is then returned by
.I 
boolarg.

.I 
Boolarg
is especially useful for parsing boolean values from argument
lists in programs using the command interpreter,
.IR ci (3).
.SH "LIBRARY NOTES"
You must link against /usr/local/lib/libcs.a to define this routine.
.SH "SEE ALSO"
.IR nxtarg (3), 
.IR getbool (3), 
.IR ci (3)
