.\" COPYRIGHT NOTICE
.\" Copyright (c) 1994 Carnegie Mellon University
.\" All Rights Reserved.
.\" 
.\" See <cmu_copyright.h> for use and distribution information.
.\" 
.\" 
.\" HISTORY
.\" $Log:	foldup.3,v $
Revision 1.1  96/06/03  19:00:21  satya
Initial revision

.\" Revision 1.2  1995/10/18  14:58:14  moore
.\" 	Created libcs man(3) pages from mach entries
.\" 	[1995/10/18  14:53:43  moore]
.\"
.\" $EndLog$
.\" Copyright (c) 1990 Carnegie Mellon University
.\" All Rights Reserved.
.\" 
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted, provided that both the copyright
.\" notice and this permission notice appear in all copies of the
.\" software, derivative works or modified versions, and any portions
.\" thereof, and that both notices appear in supporting documentation.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND CARNEGIE MELLON UNIVERSITY
.\" DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT
.\" SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE FOR ANY SPECIAL, DIRECT,
.\" INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
.\" RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
.\" CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
.\" CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" Users of this software agree to return to Carnegie Mellon any
.\" improvements or extensions that they make and grant Carnegie the
.\" rights to redistribute these changes.
.\"
.\" Export of this software is permitted only after complying with the
.\" regulations of the U.S. Deptartment of Commerce relating to the
.\" Export of Technical Data.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" HISTORY
.\" $Log:	foldup.3,v $
Revision 1.1  96/06/03  19:00:21  satya
Initial revision

.\" Revision 1.2  1995/10/18  14:58:14  moore
.\" 	Created libcs man(3) pages from mach entries
.\" 	[1995/10/18  14:53:43  moore]
.\"
.\" Revision 1.1.1.2  1995/10/18  14:53:43  moore
.\" 	Created libcs man(3) pages from mach entries
.\"
.\" Revision 1.2  90/12/12  15:50:02  mja
.\" 	Add copyright/disclaimer for distribution.
.\" 
.\" 13-Nov-86  Andi Swimmer (andi) at Carnegie-Mellon University
.\" 	Revised for 4.3.
.\" 
.\" 05-Dec-79  Steven Shafer (sas) at Carnegie-Mellon University
.\" 	Created.
.\" 
.TH FOLD 3 12/5/79
.CM 1
.SH "NAME"
foldup, folddown \- perform case-folding on strings
.SH "SYNOPSIS"
.B
char *foldup (out,in);
.br
.B
char *folddown (out,in);
.br
.B
char *out,*in;
.SH "DESCRIPTION"
.I
Foldup
and
.I
folddown
perform case-folding (to upper or lower case, respectively)
on strings.
The string at
.I
in
is copied to the buffer at
.I
out,
changing letters as appropriate.
Only letters are affected.
.sp
It is
.I
specifically allowed
for
.I
out
and
.I
in
to specify the same string; in this manner, in-place case folding
is possible.
Both folding routines return
.I
out
as their value, for convenience.
.SH "LIBRARY NOTES"
You must link against /usr/local/lib/libcs.a to define these routines.
.SH "BUGS"
No "inversion" mode is provided.
In-place case folding is accomplished
by specifying
.I
out
and
.I
in
as the same string; this is a rather cumbersome way to specify the most
common manner of case-folding.
