.\" COPYRIGHT NOTICE
.\" Copyright (c) 1994 Carnegie Mellon University
.\" All Rights Reserved.
.\" 
.\" See <cmu_copyright.h> for use and distribution information.
.\" 
.\" 
.\" HISTORY
.\" $Log: path.3,v $
.\" Revision 1.1  1996/11/22 19:19:16  braam
.\" First Checkin (pre-release)
.\"
Revision 1.1  96/06/03  19:00:57  satya
Initial revision

.\" Revision 1.2  1995/10/18  14:58:52  moore
.\" 	Created libcs man(3) pages from mach entries
.\" 	[1995/10/18  14:55:30  moore]
.\"
.\" $EndLog$
.\" Copyright (c) 1990 Carnegie Mellon University
.\" All Rights Reserved.
.\" 
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted, provided that both the copyright
.\" notice and this permission notice appear in all copies of the
.\" software, derivative works or modified versions, and any portions
.\" thereof, and that both notices appear in supporting documentation.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND CARNEGIE MELLON UNIVERSITY
.\" DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT
.\" SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE FOR ANY SPECIAL, DIRECT,
.\" INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
.\" RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
.\" CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
.\" CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" Users of this software agree to return to Carnegie Mellon any
.\" improvements or extensions that they make and grant Carnegie the
.\" rights to redistribute these changes.
.\"
.\" Export of this software is permitted only after complying with the
.\" regulations of the U.S. Deptartment of Commerce relating to the
.\" Export of Technical Data.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" HISTORY
.\" $Log: path.3,v $
.\" Revision 1.1  1996/11/22 19:19:16  braam
.\" First Checkin (pre-release)
.\"
Revision 1.1  96/06/03  19:00:57  satya
Initial revision

.\" Revision 1.2  1995/10/18  14:58:52  moore
.\" 	Created libcs man(3) pages from mach entries
.\" 	[1995/10/18  14:55:30  moore]
.\"
.\" Revision 1.1.1.2  1995/10/18  14:55:30  moore
.\" 	Created libcs man(3) pages from mach entries
.\"
.\" Revision 1.2  90/12/12  15:55:51  mja
.\" 	Add copyright/disclaimer for distribution.
.\" 
.\" 13-Nov-86  Andi Swimmer (andi) at Carnegie-Mellon University
.\" 	Revised for 4.3.
.\" 
.\" 05-Dec-79  Steven Shafer (sas) at Carnegie-Mellon University
.\" 	Created.
.\" 
.TH PATH 3 12/5/79
.CM 1
.SH "NAME"
path \- split pathname into directory and file parts
.SH "SYNOPSIS"
.B
path (pathname,direc,file);
.br
.B
char *pathname,*direc,*file;
.SH "DESCRIPTION"
.I
Path
breaks a complete pathname into a filename part and a directory part.
It handles all pathnames allowed in UNIX.
The resulting filename will
not have trailing slashes, and will not be null.
The resulting
directory name will not be null.
.sp
You provide three strings:
.I
pathname,
the complete name to be split,
.I
direc,
a buffer into which the directory part will be copied, and
.I
file,
a buffer to hold the filename part.
You must ensure that the
buffers are big enough.
.sp
The handling of most names is obvious, but several special cases
exist.
The name "f", containing no slashes, is split into
directory "." and filename "f".
The name "/" is directory "/" and
filename ".".
The path "" is directory "." and filename ".".
.SH "SEE ALSO"
.IR getwd (3),
.IR expand (3)
.SH "BUGS"
The string
.I
direc
must be big enough to hold the entire pathname, since it is used
as working storage by
.I
path.
.sp
A possible future modification to
.I
path
would add the additional proviso that the directory part
will be an absolute pathname.
The implementation of this
is simple -- you perform
.I
getwd,
and prepend the value (with a separating "/"), but only
if the original
.I
pathname
is not absolute (i.e.
does not begin with "/").
It is also
possible (but not necessary) to resolve initial "../"
substrings in
.I
pathname
at that time.
.SH "LIBRARY NOTES"
You must link against /usr/local/lib/libcs.a to define this routine.
