.\" COPYRIGHT NOTICE
.\" Copyright (c) 1994 Carnegie Mellon University
.\" All Rights Reserved.
.\" 
.\" See <cmu_copyright.h> for use and distribution information.
.\" 
.\" 
.\" HISTORY
.\" $Log: prstab.3,v $
.\" Revision 4.1  1997/01/08 21:54:01  rvb
.\" r = 4.1; fix $ HEADERS
.\"
.\" Revision 1.1  1996/11/22 19:19:29  braam
.\" First Checkin (pre-release)
.\"
Revision 1.1  96/06/03  19:01:00  satya
Initial revision

.\" Revision 1.2  1995/10/18  14:58:55  moore
.\" 	Created libcs man(3) pages from mach entries
.\" 	[1995/10/18  14:55:35  moore]
.\"
.\" $EndLog$
.\" Copyright (c) 1990 Carnegie Mellon University
.\" All Rights Reserved.
.\" 
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted, provided that both the copyright
.\" notice and this permission notice appear in all copies of the
.\" software, derivative works or modified versions, and any portions
.\" thereof, and that both notices appear in supporting documentation.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND CARNEGIE MELLON UNIVERSITY
.\" DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT
.\" SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE FOR ANY SPECIAL, DIRECT,
.\" INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
.\" RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
.\" CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
.\" CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" Users of this software agree to return to Carnegie Mellon any
.\" improvements or extensions that they make and grant Carnegie the
.\" rights to redistribute these changes.
.\"
.\" Export of this software is permitted only after complying with the
.\" regulations of the U.S. Deptartment of Commerce relating to the
.\" Export of Technical Data.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" HISTORY
.\" $Log: prstab.3,v $
.\" Revision 4.1  1997/01/08 21:54:01  rvb
.\" r = 4.1; fix $ HEADERS
.\"
.\" Revision 1.1  1996/11/22 19:19:29  braam
.\" First Checkin (pre-release)
.\"
Revision 1.1  96/06/03  19:01:00  satya
Initial revision

.\" Revision 1.2  1995/10/18  14:58:55  moore
.\" 	Created libcs man(3) pages from mach entries
.\" 	[1995/10/18  14:55:35  moore]
.\"
.\" Revision 1.1.1.2  1995/10/18  14:55:35  moore
.\" 	Created libcs man(3) pages from mach entries
.\"
.\" Revision 1.2  90/12/12  15:56:12  mja
.\" 	Add copyright/disclaimer for distribution.
.\" 
.\" 13-Nov-86  Andi Swimmer (andi) at Carnegie-Mellon University
.\" 	Revised for 4.3.
.\" 
.\" 16-Apr-80  Steven Shafer (sas) at Carnegie-Mellon University
.\" 	Created.
.\" 
.TH PRSTAB 3 4/16/80
.CM 2
.SH "NAME"
prstab, fprstab \- print string table using multiple columns
.SH "SYNOPSIS"
.B
prstab(table);
.br
.B
char **table;
.sp
.B
fprstab(file, list)
.br
.B
FILE *file;
.br
.B
char **list;
.SH "DESCRIPTION"
.I
Prstab
prints all the strings in the string table
.I
table.
It uses some heuristics to decide how many columns should be printed,
and prints the names in order reading down the columns (i.e.
column-major
order).
It's usually superior to just listing all the names in one long
column, and it's smart enough to use a single column if there are just
a few names.
.sp
The string table for
.I
prstab
can be declared just like a table for
.IR stablk (3),
i.e.:
.nf
.sp
	char *table[] = { "first", "second", ..., "last", 0};
.fi
.SH "LIBRARY NOTES"
You must link against /usr/local/lib/libcs.a to define this routine.
.SH "SEE ALSO"
.IR stablk (3)
.SH "BUGS"
Several constants are wired-in.
.I
Prstab
assumes that there are 80 columns on the page, and that a leading
tab is like 7 or 8 spaces.
It leaves 5 spaces more than the longest
of all strings between columns, and likes to print at least 8 rows
if there are just a few strings.
