title: Coda File System User and System Administrator Manual
nav:
 - index.md
 - getting_started.md
 - scenarios.md
 - system_overview.md
 - obtaining_coda.md
 - kernel.md
 - client_installation.md
 - server_installation.md
 - troubleshooting.md
 - volume_administration.md
 - user_administration.md
 - backup.md
 - reinit.md
 - quick_ref.md
 - file_list.md
 - examples.md
