option('enable-lwp', type: 'feature', value: 'enabled')
option('enable-pthread', type: 'feature', value: 'disabled')
option(
    'install-tools',
    type: 'boolean',
    value: true,
    description: 'Install the rvmutl and rdsinit tools',
)
option(
    'rpath',
    type: 'boolean',
    value: false,
    yield: true,
    description: 'embed an RPATH so installed binaries find libraries in a (non-standard) libdir',
)
