#! /bin/sh
# postinst script for coda
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule

if [ ! -f /etc/coda/venus.conf ] ; then
    # first time? we need to initialize RVM on startup.
    touch /var/lib/coda/cache/INIT

    db_get coda/realm
    codaconfedit venus.conf realm "$RET" >&2
    db_get coda/cachesize
    codaconfedit venus.conf cacheblocks "$RET" >&2
fi

#DEBHELPER#

exit 0


