option(
    'enable-pthread',
    type: 'feature',
    value: 'disabled',
    description: 'Build the experimental pthread library',
)
option(
    'rpath',
    type: 'boolean',
    value: false,
    yield: true,
    description: 'embed an RPATH so installed binaries find libraries in a (non-standard) libdir',
)
