#!/bin/sh
#
# Simple logrotation for Coda client logfiles
#

logfile=/usr/coda/etc/venus.log
errorlog=/usr/coda/etc/console
pid_file=/usr/coda/venus.cache/pid
. "`codaconfedit venus.conf`"

for i in 9 8 7 6 5 4 3 2 1 0 ; do
    j=`expr $i + 1`
    [ -f "${logfile}-$i" ]  && mv -f "${logfile}-$i"  "${logfile}-$j"
    [ -f "${errorlog}-$i" ] && mv -f "${errorlog}-$i" "${errorlog}-$j"
done

[ -f "${logfile}" ]  && mv -f "${logfile}"  "${logfile}-0"
[ -f "${errorlog}" ] && mv -f "${errorlog}" "${errorlog}-0"

# Tell venus to reopen the logfiles
kill -HUP `cat ${pid_file}` 2>/dev/null

# alternatively use one of the following,
# vutil swap
# killall -HUP venus

