.if n .ds Q \&"
.if t .ds Q ``
.if n .ds U \&"
.if t .ds U ''
.TH "createvol_rep" 8 
.tr \&
.nr bi 0
.nr ll 0
.nr el 0
.de DS
..
.de DE
..
.de Pp
.ie \\n(ll>0 \{\
.ie \\n(bi=1 \{\
.nr bi 0
.if \\n(t\\n(ll=0 \{.IP \\(bu\}
.if \\n(t\\n(ll=1 \{.IP \\n+(e\\n(el.\}
.\}
.el .sp 
.\}
.el \{\
.ie \\nh=1 \{\
.LP
.nr h 0
.\}
.el .PP 
.\}
..
.SH NAME  
createvol_rep \- create read-write replicated volume

.SH SYNOPSIS

.Pp
\fBcreatevol_rep\fP <volume-name> <server>[/<partition>] [<server>[/partition]]... [<volume-id>]
.Pp
.Pp
.Pp
.SH DESCRIPTION

.Pp
\fBcreatevol_rep\fP is a front end to \fIvolutil create_rep\fP and is used to
create a Coda read/write replicated volume. The invoker must specify the
volume name (\fI<volume-name>)\fP, and the server(s) on which the
volume should be created. (\fI<server>[/<partition>])\fP, the partition name
is required when the server manages more than one data partition. Finally an
replicated \fI<volume-id>\fP\& can be specified.
.Pp
\fBcreatevol_rep\fP first checks in  \fI/vice/vol/AllVolumes\fP and 
\fI/vice/vol/VRList\fP to see if the volume name already exists.  If not, 
it uses the \fIvolutil create_rep\fP command to create the volume at each of 
the replication sites.  It then rebuilds the Volume Location Data Base (VLDB)
and the Volume Replication Data Base (VRDB).
.Pp
The optional replicated \fI<volume-id>\fP specifies the \&"replicated\&"
volumeid of the volume being created.  By default, the volume id in
\fI/vice/vol/maxgroupid\fP is used.  Each time it is used it is also updated
by adding 1 to it.
.Pp
After the replicas are created at each replication site, a new VLDB is built
automatically using \fIbldvldb.sh\fP(8), and the Volume Replication
List in \fI/vice/vol/VRList\fP is updated.  The VRList contains one line for 
each replicated volume.  Each line specifies the replicated volume name, 
replicated volume id, number of replication sites, and the local volume id at
each replication site.  This file is now used to create a new Volume
Replication Data Base (VRDB) using the \fI\&"volutil makevrdb /vice/vol/VRList\&"\fP command.
.Pp
.Pp
.SH EXAMPLES

.Pp
To create a replicated volume \&"coda.rep\&" on 3 sites foo, bar and  gorp use:
.Pp
.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fBcreatevol_rep coda.rep foo bar gorp\fP"
.nr bi 1
.Pp
.if \n(ll>1 .RE
.nr ll -1
.Pp
To assign a predetermined replicated volume id, use
.Pp
.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fBcreatevol_rep coda.rep foo bar gorp 7F000003\fP"
.nr bi 1
.Pp
.if \n(ll>1 .RE
.nr ll -1
.Pp
where \&"7F000003\&" is the replicated volume id.
.Pp
.Pp
.Pp
.SH DIAGNOSTICS

.Pp
This command must be issued at the System Control Machine (SCM).  Also, it 
must be invoked with effective user id of root.  This command does not check 
for return codes from the \fIvolutil create_rep\fP command.  The invoker 
must check \fI/vice/vol/VRList\fP and \fI/vice/vol/VolumeList\fP at each 
replication site to see if the volume was created.
.Pp
.Pp
.Pp
.SH FILES

.Pp
.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fI/vice/vol/VRList\fP"
.nr bi 1
.Pp
contains information on replicated volumes 
.Pp
.if \n(ll>1 .RE
.nr ll -1

.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fI/vice/vol/VolumeList\fP"
.nr bi 1
.Pp
name of volume created at each site is appended to it 
.Pp
.if \n(ll>1 .RE
.nr ll -1

.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fI/vice/db/VRDB\fP"
.nr bi 1
.Pp
is used to describe the replicated volumes in terms of its non-replicated members.
.Pp
.if \n(ll>1 .RE
.nr ll -1

.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fI/vice/vol/AllVolumes\fP"
.nr bi 1
.Pp
is used to check if volume exists 
.Pp
.if \n(ll>1 .RE
.nr ll -1

.nr ll +1
.nr t\n(ll 2
.if \n(ll>1 .RS
.IP "\fI/vice/vol/maxgroupid\fP"
.nr bi 1
.Pp
is used to assign a volume id to the replicated volume
.Pp
.if \n(ll>1 .RE
.nr ll -1
.Pp
.Pp
.Pp
.SH SEE ALSO

.Pp
bldvldb.sh (8), volutil (8)
.Pp
.Pp
.Pp
.SH AUTHOR

.Pp
Puneet Kumar, 1990, Created
.Pp
