#!/bin/csh -f 
#ifndef _BLURB_
#define _BLURB_
#/*
#
#            Coda: an Experimental Distributed File System
#                             Release 4.0
#
#          Copyright (c) 1987-1996 Carnegie Mellon University
#                         All Rights Reserved
#
#Permission  to  use, copy, modify and distribute this software and its
#documentation is hereby granted,  provided  that  both  the  copyright
#notice  and  this  permission  notice  appear  in  all  copies  of the
#software, derivative works or  modified  versions,  and  any  portions
#thereof, and that both notices appear in supporting documentation, and
#that credit is given to Carnegie Mellon University  in  all  documents
#and publicity pertaining to direct or indirect use of this code or its
#derivatives.
#
#CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
#SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
#FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
#DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
#RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
#ANY DERIVATIVE WORK.
#
#Carnegie  Mellon  encourages  users  of  this  software  to return any
#improvements or extensions that  they  make,  and  to  grant  Carnegie
#Mellon the rights to redistribute these changes without encumbrance.
#*/
#
#static char *rcsid = "$Header: blurb.doc,v 1.1 96/11/22 13:29:31 raiff Exp $";
#endif /*_BLURB_*/


#ifndef _BLURB_
#define _BLURB_
#/*
#
#            Coda: an Experimental Distributed File System
#                             Release 3.1
#
#          Copyright (c) 1987-1995 Carnegie Mellon University
#                         All Rights Reserved
#
#Permission  to  use, copy, modify and distribute this software and its
#documentation is hereby granted,  provided  that  both  the  copyright
#notice  and  this  permission  notice  appear  in  all  copies  of the
#software, derivative works or  modified  versions,  and  any  portions
#thereof, and that both notices appear in supporting documentation, and
#that credit is given to Carnegie Mellon University  in  all  documents
#and publicity pertaining to direct or indirect use of this code or its
#derivatives.
#
#CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
#SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
#FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
#DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
#RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
#ANY DERIVATIVE WORK.
#
#Carnegie  Mellon  encourages  users  of  this  software  to return any
#improvements or extensions that  they  make,  and  to  grant  Carnegie
#Mellon the rights to redistribute these changes without encumbrance.
#*/
#
#static char *rcsid = "$Header: initmtpts,v 1.1 96/11/22 13:25:36 raiff Exp $";
#endif /*_BLURB_*/



/usr/coda/bin/fs mkmount /coda/usr rep.usr
/usr/coda/bin/fs mkmount /coda/project rep.project
/usr/coda/bin/fs mkmount /coda/tmp rep.tmp
/usr/coda/bin/fs mkmount /coda/nonrepr coda.nonrep.ravel
/usr/coda/bin/fs mkmount /coda/nonrepm coda.nonrep.mahler
/usr/coda/bin/fs mkmount /coda/nonrepv coda.nonrep.vivaldi
mkdir /coda/project/coda
/usr/coda/bin/fs mkmount /coda/project/coda/alpha project.coda.alpha.rep 
/usr/coda/bin/fs mkmount /coda/project/coda/beta project.coda.beta.rep 
/usr/coda/bin/fs mkmount /coda/project/coda/kernel project.coda.kernel.rep 
/usr/coda/bin/fs mkmount /coda/project/coda/src project.coda.src.rep 
/usr/coda/bin/fs mkmount /coda/usr/jjk rep.jjk
/usr/coda/bin/fs mkmount /coda/usr/dcs rep.dcs
/usr/coda/bin/fs mkmount /coda/usr/satya rep.satya
/usr/coda/bin/fs mkmount /coda/usr/meo rep.meo
/usr/coda/bin/fs mkmount /coda/usr/pkumar rep.pkumar
/usr/coda/bin/fs mkmount /coda/usr/mashburn rep.mashburn

foreach DIR (/coda /coda/tmp /coda/usr /coda/project /coda/nonrepr /coda/nonrepm /coda/nonrepv /coda/project/coda /coda/project/coda/alpha /coda/project/coda/beta /coda/project/coda/kernel /coda/project/coda/src)
/usr/coda/bin/fs sa $DIR System:coda all
/usr/coda/bin/fs sa $DIR System:AnyUser rl 
end #FOREACH

foreach DIR (pkumar satya jjk dcs meo mashburn)
/usr/coda/bin/fs sa /coda/usr/$DIR $DIR all
/usr/coda/bin/fs sa /coda/usr/$DIR System:AnyUser rl
end #FOREACH



