#!/bin/csh -f
#ifndef _BLURB_
#define _BLURB_
#/*
#
#            Coda: an Experimental Distributed File System
#                             Release 4.0
#
#          Copyright (c) 1987-1996 Carnegie Mellon University
#                         All Rights Reserved
#
#Permission  to  use, copy, modify and distribute this software and its
#documentation is hereby granted,  provided  that  both  the  copyright
#notice  and  this  permission  notice  appear  in  all  copies  of the
#software, derivative works or  modified  versions,  and  any  portions
#thereof, and that both notices appear in supporting documentation, and
#that credit is given to Carnegie Mellon University  in  all  documents
#and publicity pertaining to direct or indirect use of this code or its
#derivatives.
#
#CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
#SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
#FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
#DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
#RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
#ANY DERIVATIVE WORK.
#
#Carnegie  Mellon  encourages  users  of  this  software  to return any
#improvements or extensions that  they  make,  and  to  grant  Carnegie
#Mellon the rights to redistribute these changes without encumbrance.
#*/
#
#static char *rcsid = "$Header: /coda/coda.cs.cmu.edu/project/coda/cvs/coda/coda-src/scripts/Attic/initfs,v 4.1 1997/01/08 21:50:49 rvb Exp $";
#endif /*_BLURB_*/


#ifndef _BLURB_
#define _BLURB_
#/*
#
#            Coda: an Experimental Distributed File System
#                             Release 3.1
#
#          Copyright (c) 1987-1995 Carnegie Mellon University
#                         All Rights Reserved
#
#Permission  to  use, copy, modify and distribute this software and its
#documentation is hereby granted,  provided  that  both  the  copyright
#notice  and  this  permission  notice  appear  in  all  copies  of the
#software, derivative works or  modified  versions,  and  any  portions
#thereof, and that both notices appear in supporting documentation, and
#that credit is given to Carnegie Mellon University  in  all  documents
#and publicity pertaining to direct or indirect use of this code or its
#derivatives.
#
#CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
#SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
#FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
#DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
#RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
#ANY DERIVATIVE WORK.
#
#Carnegie  Mellon  encourages  users  of  this  software  to return any
#improvements or extensions that  they  make,  and  to  grant  Carnegie
#Mellon the rights to redistribute these changes without encumbrance.
#*/
#
#static char *rcsid = "$Header: /coda/coda.cs.cmu.edu/project/coda/cvs/coda/coda-src/scripts/Attic/initfs,v 4.1 1997/01/08 21:50:49 rvb Exp $";
#endif /*_BLURB_*/



# Ensure that this is the SCM
if (`cat /.hostname` != `cat /.scm`) then
	echo This must be run from the scm (`cat /.scm`)
	exit
endif

# Create non-replicated volumes
#echo > /vice/vol/AllVolumes
#/vice/bin/createvol coda.root mahler /vicepa
#/vice/bin/createvol coda.nonrep.mahler mahler /vicepa
#/vice/bin/createvol coda.nonrep.vivaldi vivaldi /vicepa
#/vice/bin/createvol coda.nonrep.ravel ravel /vicepa

# Create replicated volumes
echo "E0000100\
E0000101 mahler\
E0000102 vivaldi\
E0000103 mahler vivaldi\
E0000104 ravel\
E0000105 mahler ravel\
E0000106 vivaldi ravel\
E0000107 mahler vivaldi ravel" > /vice/db/VSGDB
echo 2130706433 > /vice/vol/maxgroupid
echo > /vice/vol/VRList

/vice/bin/createvol_rep rep.project E0000107 
/vice/bin/createvol_rep rep.usr E0000107
/vice/bin/createvol_rep rep.tmp E0000107
/vice/bin/createvol_rep project.coda.alpha.rep E0000107 
/vice/bin/createvol_rep project.coda.beta.rep E0000107 
/vice/bin/createvol_rep project.coda.kernel.rep E0000107 
/vice/bin/createvol_rep project.coda.src.rep E0000107 
/vice/bin/createvol_rep rep.dcs E0000107
/vice/bin/createvol_rep rep.jjk E0000107
/vice/bin/createvol_rep rep.satya E0000107
/vice/bin/createvol_rep rep.meo E0000107
/vice/bin/createvol_rep rep.pkumar E0000107
/vice/bin/createvol_rep rep.mashburn E0000107

