#!/bin/sh
#ifndef _BLURB_
#define _BLURB_
#/*
#
#            Coda: an Experimental Distributed File System
#                             Release 4.0
#
#          Copyright (c) 1987-1996 Carnegie Mellon University
#                         All Rights Reserved
#
#Permission  to  use, copy, modify and distribute this software and its
#documentation is hereby granted,  provided  that  both  the  copyright
#notice  and  this  permission  notice  appear  in  all  copies  of the
#software, derivative works or  modified  versions,  and  any  portions
#thereof, and that both notices appear in supporting documentation, and
#that credit is given to Carnegie Mellon University  in  all  documents
#and publicity pertaining to direct or indirect use of this code or its
#derivatives.
#
#CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
#SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
#FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
#DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
#RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
#ANY DERIVATIVE WORK.
#
#Carnegie  Mellon  encourages  users  of  this  software  to return any
#improvements or extensions that  they  make,  and  to  grant  Carnegie
#Mellon the rights to redistribute these changes without encumbrance.
#*/
#
#static char *rcsid = "$Header: /coda/coda.cs.cmu.edu/project/coda/cvs/coda/coda-src/scripts/Attic/startserver,v 4.13 1998/08/05 23:49:53 braam Exp $";
#endif /*_BLURB_*/

if [ -f /vice/srv/pid ]; then
    echo "Can't start file server, one is already running!"
    exit 1 
fi 

# Remove outdated logfiles
mv /vice/srv/SrvErr /vice/srv/SrvErr.prev
rm -f /vice/srv/SrvLog-7
rm -f /vice/srv/CRASH

# pass on arguments to srv
# The -rvm flag takes 3 arguments. The first is the log device/file,
# the second is the data segment device/file, and the third is the
# length of the file or device holding the RVM data segment.
# These parameters are taken from /vice/srv.conf

codasrv $* -t 1000 -trunc 5 -debarrenize -nosalvageonshutdown -nodumpvm `grep '^\-rvm ' /vice/srv.conf`

rm -f /vice/srv/pid
