#!/bin/sh
# BLURB gpl
# 
#                            Coda File System
#                               Release 5
# 
#           Copyright (c) 1987-1999 Carnegie Mellon University
#                   Additional copyrights listed below
# 
# This  code  is  distributed "AS IS" without warranty of any kind under
# the terms of the GNU General Public Licence Version 2, as shown in the
# file  LICENSE.  The  technical and financial  contributors to Coda are
# listed in the file CREDITS.
# 
#                         Additional copyrights
#                            none currently
# 
#*/

if [ -f /vice/srv/pid ]; then
    echo "Can't start file server, one is already running!"
    exit 1 
fi 

# Remove outdated logfiles
mv /vice/srv/SrvErr /vice/srv/SrvErr.prev
rm -f /vice/srv/SrvLog-7
rm -f /vice/srv/CRASH

# pass on arguments to srv
# The -rvm flag takes 3 arguments. The first is the log device/file,
# the second is the data segment device/file, and the third is the
# length of the file or device holding the RVM data segment.
# These parameters are taken from /vice/srv.conf

codasrv $* -t 1000 -trunc 5 -debarrenize -nosalvageonshutdown -nodumpvm `grep '^\-rvm ' /vice/srv.conf`

rm -f /vice/srv/pid
