#!/bin/sh
#ifndef _BLURB_
#define _BLURB_
#/*
#
#            Coda: an Experimental Distributed File System
#                             Release 4.0
#
#          Copyright (c) 1987-1996 Carnegie Mellon University
#                         All Rights Reserved
#
#Permission  to  use, copy, modify and distribute this software and its
#documentation is hereby granted,  provided  that  both  the  copyright
#notice  and  this  permission  notice  appear  in  all  copies  of the
#software, derivative works or  modified  versions,  and  any  portions
#thereof, and that both notices appear in supporting documentation, and
#that credit is given to Carnegie Mellon University  in  all  documents
#and publicity pertaining to direct or indirect use of this code or its
#derivatives.
#
#CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
#SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
#FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
#DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
#RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
#ANY DERIVATIVE WORK.
#
#Carnegie  Mellon  encourages  users  of  this  software  to return any
#improvements or extensions that  they  make,  and  to  grant  Carnegie
#Mellon the rights to redistribute these changes without encumbrance.
#*/
#
#static char *rcsid = "$Header: /coda/coda.cs.cmu.edu/project/coda/cvs/coda/coda-src/scripts/Attic/startserver,v 4.3 1997/12/10 16:46:17 braam Exp $";
#endif /*_BLURB_*/

echo "BEFORE USE EDIT ME TO SET UP DIFFERENTLY FOR EACH SERVER"
exit

if [ -f /vice/srv/pid ]; then
    echo "Can't start file server, one is already running!"
    exit 1 
fi 

# Install a new file server. Using this hopefully prevents one from
# overwritting an executing binary.

if [ -f /vice/bin/srv.new ]; then
    echo "Installing new file server."
    mv /vice/bin/srv /vice/bin/srv.old
    mv /vice/bin/srv.new /vice/bin/srv
fi

# Remove outdated logfiles
rm /vice/srv/SrvErr
rm /vice/srv/SrvLog-7
rm -f /vice/src/CRASH

# pass on arguments to srv
# The -rvm flag takes 3 arguments. The first is the log device/file,
# the second is the data segment device/file, and the third is the
# length of the data segment file or device (Note: not the amount of
# data in the segment)
# The values used below are the default values used at CMU.

#/vice/bin/srv $* -nodumpvm -rvm /dev/rrz0g /dev/rrz0h 69206016
echo You need to edit this script to set the parameters appropriately\!

rm /vice/srv/pid

