#!/bin/sh
#
# Coda client installation script
# Made for Linux coda-client rpm distribution 
# Peter J. Braam, Dec 1996
# included suggestions from Elliot Lee, may 1997.
#
# Usage: venus-setup comma,separated,list,of,servers [cachesize in kb]
#
# the script will verify that the necessary directories and /etc/services
# are present.
#
# BUGS: need to substitute /etc/coda with @sysconfdir@ and have configure
#	splice in the right location of the venus.conf file.

if [ $# != 2 ]; then
	echo "Usage: $0 comma,separated,list,of,servers cachesize-in-kb"
	exit 1
else
	SERVERS=$1
	CACHESIZE=$2
fi

#
# Allowing the user to edit venus.conf before creating all the various
# directories might be nice, but breaks the existing `half-automatic'
# installation
#
#restart=0
#[ ! -f /etc/coda/venus.conf ] && restart=1

codaconfedit venus.conf rootservers "$SERVERS"
codaconfedit venus.conf cacheblocks "$CACHESIZE"

#if [ $restart = 1 ] ; then
#    echo "We just created an initial configuration file /etc/coda/venus.conf"
#    echo "You might want to look it over and modify some of the default paths"
#    echo "Rerun 'venus-setup $SERVERS $CACHESIZE' if you're happy"
#    exit
#fi

# default paths
errorlog=/usr/coda/etc/console
cachedir=/usr/coda/venus.cache
checkpointdir=/usr/coda/spool
logfile=/usr/coda/etc/venus.log
marinersocket=/usr/coda/spool/mariner
pid_file=/usr/coda/venus.cache/pid
run_control_file=/usr/coda/venus.cache/VENUS_CTRL
rvm_log=/usr/coda/LOG
rvm_data=/usr/coda/DATA
codatmpdir=/usr/coda/tmp

# override with user defined paths
if [ -f /etc/coda/venus.conf ] ; then
    . /etc/coda/venus.conf
fi

#
# we need to make sure we have the following directories so that venus can
# create the files that live in them.
#
errlogdir=`dirname $errorlog`
logfiledir=`dirname $logfile`
marinersocketdir=`dirname $marinersocket`
pid_filedir=`dirname $pid_file`
run_control_file_dir=`dirname $run_control_file`
rvm_logdir=`dirname $rvm_log`
rvm_datadir=`dirname $rvm_data`

# Darn, mkdir -p -m 700 /path/to/new/dir only sets the mode of the last
# created directory correctly. The following function sets the mode of all
# newly created directories.
makedir () {
  [ "$2" = "" ] && return
  while [ ! -d $2 ] ; do
    dir=$2
    # find first existing parent
    while [ "$dir" != "" -a ! -d $dir ] ; do
	newdir=`basename $dir`
	dir=`dirname $dir`
    done
    echo "Creating $dir/$newdir, mode $1"
    mkdir $dir/$newdir
    chmod $1 $dir/$newdir
  done
}

makedir 755 $checkpointdir
makedir 755 $codatmpdir
makedir 755 $marinersocketdir
makedir 755 $mountpoint
makedir 700 $cachedir
makedir 700 $errorlogdir
makedir 700 $logfiledir
makedir 700 $pid_filedir
makedir 700 $run_crontrol_file_dir
makedir 700 $rvm_logdir
makedir 700 $rvm_datadir

# set up the /coda root if it isn't there yet
if [ ! -f $mountpoint/NOT_REALLY_CODA ]; then 
 echo 'If you can see this file, venus is not running.' > \
	$mountpoint/NOT_REALLY_CODA
fi

# next run will always initialize
touch $cachedir/INIT

if [ -f /usr/coda/etc/vstab ] ; then
    echo "To avoid confusion, remove /usr/coda/etc/vstab, we have switched to"
    echo "the /etc/coda/venus.conf file for configuring the client."
fi

# make the psdev
if [ ! -c /dev/coda0 -a ! -c /dev/cfs0 -a ! -c /dev/coda/0 ] ; then
    ( cd /dev ; ./MAKEDEV cfs )
fi

# tell the kernel about the new module 
if [ X`uname` = XLinux -a ! -f /etc/debian_version ]; then 
    MODULES=/etc/conf.modules
    [ -f /etc/modules.conf ] && MODULES=/etc/modules.conf
    if ! grep coda $MODULES > /dev/null; then
        echo >> $MODULES
        echo 'alias char-major-67 coda' >> $MODULES
    fi
    /sbin/depmod -a
fi

# Setup the ports
[ ! -f /etc/debian_version ] && coda-setup-ports

