.if n .ds Q \&"
.if t .ds Q ``
.if n .ds U \&"
.if t .ds U ''
.TH "venus-setup" 8
.tr \&
.nr bi 0
.nr ll 0
.nr el 0
.de DS
..
.de DE
..
.de Pp
.ie \\n(ll>0 \{\
.ie \\n(bi=1 \{\
.nr bi 0
.if \\n(t\\n(ll=0 \{.IP \\(bu\}
.if \\n(t\\n(ll=1 \{.IP \\n+(e\\n(el.\}
.\}
.el .sp 
.\}
.el \{\
.ie \\nh=1 \{\
.LP
.nr h 0
.\}
.el .PP 
.\}
..
.SH NAME  

.Pp
\fBvenus-setup\fP setup \fBvenus\fP on a client
.Pp
.SH SYNOPSIS

.Pp
\fBvenus-setup\fP [comma,separated,list,of,servers] [cachesize in kb]
.Pp
.Pp
.SH DESCRIPTION

.Pp
The \fBvenus-setup\fP command takes a list of servers separated
by commas, one of which must be the SCM and a cache size given in 
kilobytes.  \fINOTE\fP: at least one server must be specified.  And
if only one server is specified, it must be the SCM for the Coda Cell.
\fBVenus-setup\fP then performs the following operations:
.nr ll +1
.nr t\n(ll 0
.if \n(ll>1 .RS
.nr bi 1
.Pp
Creates the \fI/coda\fP mount point if not present.
.nr bi 1
.Pp
Creates \fI/usr/coda\fP if not present.
.nr bi 1
.Pp
Creates necessary subdirectories under \fI/usr/coda\fP if not present.
.nr bi 1
.Pp
Creates \fI/usr/coda/etc/vstab\fP with parameters given on the 
command line.
.nr bi 1
.Pp
Creates \fI/dev/cfs0\fP if not already present.
.nr bi 1
.Pp
Adds Coda filesystem port numbers to \fI/etc/servers\fP if not present.
.if \n(ll>1 .RE
.nr ll -1
.Pp
.SH EXAMPLE

.Pp
.Pp
.DS
.sp 
.ft RR
.nf

Venus-setup Mickey,Minnie,Goofy 10000
.DE
.fi 
.ec
.ft P
.sp

Sets up, \fI/usr/coda/etc/vstab\fP, for \fBvenus\fP to 
contact either Mickey, Minnie or Goofy and configures venus with a 10MB 
cache.
.Pp
.SH BUGS

.Pp
The [cachesize in kb] option to venus-setup is not very smart.  In
fact, it is quite dumb.  No abbreviations are allowed after the
number and the number is taken literally to be kilobytes.
.Pp
\fBVenus-setup\fP will happily overwrite an existing, 
\fI/usr/coda/etc/vstab\fP, without warning.
.Pp
.SH FILES

.Pp
\fI/etc/services\fP: the Internet network services list.
\fI/usr/coda/etc/vstab\fP: the VenuS TABle specification file.
.Pp
.SH SEE ALSO

.Pp
venus (8), vstab (5), services (5), servers (5)
.Pp

Coda Manual: ``Installing A Coda Client''
.Pp
.Pp
.SH AUTHOR

.Pp
Henry M. Pierce, 1998, created
.Pp
