#!/bin/sh
# last figure is volid.  Must be unique. Normally
# createvol and createvol_rep will automatically 
# generate a unique number like that.

createvol_rep codaroot E0000100 /vicepa

echo codaroot > /ROOTVOLUME
