#!/bin/sh

#
# Setting up the server directory
#

echo Your server directory will hold the files \(not directories\). 
echo It must be "/vicepa" in this initial release of Coda, but
echo I can make that a symlink to another directory.
echo
echo -n 'Where shall we store your data [/vicepa]? '
srvdir=/vicepa
read srvdir

if [ x$srvdir = x ]; then
    srvdir=/vicepa
fi

if [ x$srvdir != x/vicepa ]; then
    symlink=y
else
    symlink=n
fi

# set up a symlink if needed
if [ $symlink = y ]; then
    # does srvdir exist? if so, exit
    if [ ! -d $srvdir ]; then
	mkdir $srvdir
	if [ $? != 0 ]; then
	    echo "Cannot create $srvdir. Exiting."
	    exit 1
	fi
    fi
    if [ -d /vicepa ]; then
	echo /vicepa exists as directory. Exiting.
	exit 1
    fi
    ln -sf $srvdir /vicepa
    ln -sf /vicepa /mnt/vice
    if [ $? != 0 ]; then
	echo Cannot create symlink /vicepa pointing to $srvdir.
	    echo Exiting.
	    exit 1
    fi
else # use /vicepa as a directory
    if [  -e /vicepa -a ! -d /vicepa ]; then
	echo /vicepa exists, but is not a directory. Exiting.
	exit 1
    fi
    if [ ! -d /vicepa ]; then
	mkdir /vicepa
	ln -sf /vicepa /mnt/vice
    fi
fi

echo Server directory is set up!
echo
