#!/bin/sh
# BLURB gpl
# 
#                            Coda File System
#                               Release 5
# 
#           Copyright (c) 1987-1999 Carnegie Mellon University
#                   Additional copyrights listed below
# 
# This  code  is  distributed "AS IS" without warranty of any kind under
# the terms of the GNU General Public Licence Version 2, as shown in the
# file  LICENSE.  The  technical and financial  contributors to Coda are
# listed in the file CREDITS.
# 
#                         Additional copyrights
#                            none currently
# 
#*/

INSTALLBASE=/vice
OBJS=$2
VERS=$1

if  [ $# != 2 ]; then
    echo "Usage: $0  {alpha,beta-version-no}<object base dir>"
    exit 1
fi

# sanity
SRVPIDFILE=/vice/srv/pid
if [ -e $SRVPIDFILE ]; then
    echo "A server is running!"
    exit 1
fi

if [ ! -e ${INSTALLBASE}/bin ]; then
        echo "First time eh? Setting up ${INSTALLBASE}/bin"
	ln -s /tmp ${INSTALLBASE}/bin
fi

if [ ! -e ${INSTALLBASE}/bin.old ]; then
        echo "First time eh? Setting up ${INSTALLBASE}/bin.old"
	ln -s /tmp ${INSTALLBASE}/bin.old
fi

if [ ! -L ${INSTALLBASE}/bin ]; then
	echo "${INSTALLBASE}/bin must be a symlink! Fix this first."
	exit 1
fi

if [ ! -L ${INSTALLBASE}/bin.old ]; then
	echo "${INSTALLBASE}/bin must be a symlink! Fix this first."
	exit 1
fi

# leave installation information
if [ X$VERS = Xalpha ]; then 
    NEW=${INSTALLBASE}/bin.`date  +'%a-%d%b%y-%H:%M:%S'`
    mkdir $NEW
else
    NEW=${INSTALLBASE}/$1
    mkdir $NEW
    echo "Coda Beta Version $1." > ${NEW}/install-info
    echo "Installed on `date`" >> ${NEW}/install-info 
    echo "Objects used taken from $OBJS" >> ${NEW}/install-info
fi		

OLD=${INSTALLBASE}/bin.old

if [ `uname` = NetBSD ]; then
    alias make=gmake
fi


# change current bin to bin.old
cd $INSTALLBASE
rm bin.old
mv bin bin.old

# make new bin and install
ln -s $NEW bin
cd $OBJS
make TOPOBJ=$OBJS SBINDIR=$NEW BINDIR=$NEW qserver-install
if [ $? != 0 ]; then
	echo "***** WARNING: install failed. *******"
	echo "restoring ${INSTALLBASE}/bin.."
	rm bin
	mv bin.old bin
	echo "Cleanup \"$NEW\" yourself and reestablish bin.old"
fi

echo "copying start scripts"
cd $INSTALLBASE
cp -p ${OLD}/startserver $NEW


