#!/bin/sh

# Set up password and group files for Coda

cd /vice/db

echo "Setting up users and groups for Coda"
echo
echo "You need to give me a uid (not 0) and username (not root)"
echo "for a Coda System:Administrator member on this server,"
echo "(sort of a Coda super user)"
echo

echo -n "Enter the uid of this user: "
read userid

if [ x$userid = x ]; then
    echo "Nothing cannot be a Coda administrator"
    echo "Run vice-setup-user again"
    exit 1
fi

if [ x$userid = x0 ]; then
    echo "Root cannot be a Coda administrator"
    echo "Run vice-setup-user again"
    exit 1
fi

echo -n "Enter the username of this user: "
read username

if [ x$username = x ]; then
    echo "Nothing cannot be a Coda administrator"
    echo "Run vice-setup-user again"
    exit 1
fi

if [ x$userid = xroot ]; then
    echo "Root cannot be a Coda administrator"
    echo "Run vice-setup-user again"
    exit 1
fi

echo "System:Administrators   -204    $username" > group.coda
echo $username::$userid::Administrator:: > user.coda

pwd2pdb -u user.coda -g group.coda > vice.pdb
pcfgen vice.pdb

echo "$userid	changeme	admin user" > passwd.coda
initpw -k "drseuss " < passwd.coda > auth2.pw

echo "An initial administrative user $username (id $userid)"
echo "with Coda password changeme now exists."
