#!/bin/sh

# frobnicate /etc/services
NEWSERVICES=/tmp/services.$$

if grep coda_filesrv /etc/services >/dev/null ; then 
echo Removing old Coda entries from /etc/services..
perl -n -e 'if ( ! /^coda/ ) { print ; }'  < /etc/services > $NEWSERVICES
mv $NEWSERVICES /etc/services
rm $NEWSERVICES
fi 

if grep rpc2portmap /etc/services >/dev/null ; then 
echo "/etc/services already has new services registered! Good."
else 
cat <<EOF >> /etc/services
# Iana allocated Coda filesystem port numbers
rpc2portmap     369/tcp    
rpc2portmap     369/udp    # Coda portmapper
codaauth2       370/tcp    
codaauth2       370/udp    # Coda authentication server

venus           2430/tcp   # codacon port
venus           2430/udp   # Venus callback/wbc interface 
venus-se        2431/tcp   # tcp side effects
venus-se        2431/udp   # udp sftp side effect
codasrv         2432/tcp   # not used
codasrv         2432/udp   # server port
codasrv-se      2433/tcp   # tcp side effects
codasrv-se      2433/udp   # udp sftp side effect
EOF
fi

echo "/etc/services ready for Coda"
