#!/bin/sh
# BLURB gpl
# 
#                            Coda File System
#                               Release 5
# 
#           Copyright (c) 1987-1999 Carnegie Mellon University
#                   Additional copyrights listed below
# 
# This  code  is  distributed "AS IS" without warranty of any kind under
# the terms of the GNU General Public Licence Version 2, as shown in the
# file  LICENSE.  The  technical and financial  contributors to Coda are
# listed in the file CREDITS.
# 
#                         Additional copyrights
#                            none currently
# 
#*/


prog=$0
kill=/bin/kill
vpid=`/bin/cat /usr/coda/venus.cache/pid`
ckpfile=/usr/coda/venus.cache/DUMP
copfile=/usr/coda/venus.cache/COPMODES
mcfile=/usr/coda/venus.cache/MCAST
debugfile=/usr/coda/venus.cache/DEBUG

usage ()
{
    echo Usage: 
    echo ${prog} ckp
    echo ${prog} cs 
    echo ${prog} d debug_level 
    echo ${prog} "m {0,2,3,6,7}"
    echo ${prog} "mc {0,1} "
    echo ${prog} "p {0,1} "
    echo ${prog} shutdown 
    echo ${prog} stats 
    echo ${prog} swap
    if [ `uname` = Linux ]; then
	echo ${prog} kdebug level
	echo ${prog} ktrace {0,1}
    fi
    exit 1
}

if  [ $# = 0 ]; then 
    usage
fi

# strip the - from the command.  
if [ x$BASH_VERSION != x ] ; then
par=${1#-}
else
par=`echo $1 | sed -e "s/-//"`
fi
#echo $par

case $par in
	ckp )
	    echo > ${ckpfile}
	    ${kill} -USR1 ${vpid}
	    ;;

	m )
	    if [ x$2 = x0 ]; then  usage ; fi
	    val="$2"
	    if [ "$val" != 0 -a "$val" != 2 -a "$val" != 3 -a "$val" != 6 -a "$val" != 7 ]; then
		usage
	    fi
	    echo "$val" > ${copfile}
	    ${kill} -USR1 ${vpid}
	    ;;

	cs )
	    ${kill} -XFSZ ${vpid}
	    ;;

	d )
	    if [ x$2 = x ]; then  usage ; fi
	    echo "$2 $3" > ${debugfile}
	    ${kill} -USR1 ${vpid}
	    ;;

	mc )
	    if [ x$2 = x ]; then  usage ; fi
	    if  [ x$3 != x -a "$3" != 1 ]; then usage ; fi
	    echo "$2 $3" > ${mcfile}
	    ${kill} -USR1 ${vpid}
	    ;;

	p )
	    if [ x$2 = x ]; then  usage ; fi
	    val="$2"
	    if [ $val = 0 ]; then
		${kill} -EMT ${vpid}
	    else
		if [ "$val" != 1 ]; then usage ; fi
		${kill} -IOT ${vpid}
	    fi
	    ;;

	shutdown )
	    ${kill} -TERM ${vpid}
	    ;;

	stats )
	    ${kill} -XCPU ${vpid}
	    ;;

	swap )
	    ${kill} -VTALRM ${vpid}
	    ;;

	kdebug )
	    if [ `uname` != Linux -o x$2 = x ]; then usage ; fi
            echo $2 > /proc/sys/coda/debug
	    ;;

	ktrace )
	    if [ `uname` != Linux -o x$2 = x ]; then usage ; fi
            echo $2 > /proc/sys/coda/printentry
	    ;;


	* )
	    echo "${prog}: unknown switch ($1)"
	    usage
	    ;;
esac

exit 0

