.TH "CPASSWD" "1" "25 April 2005" "Coda Distributed File System" ""

.SH NAME
cpasswd \- Change Coda login password
.SH SYNOPSIS

\fBcpasswd\fR [ \fB-h \fIhost\fB\fR ] \fB[username][@realm]\fR

.SH "DESCRIPTION"
.PP
This command sets the Coda password for the current user.
.PP
\fBcpasswd\fR prompts for the users old password, and
then for the new one. The new password must be typed twice, to forestall
mistakes. Change requests can be aborted by typing a carriage return when
prompted for the new password.
.PP
\fBcpasswd\fR won't be able to change the users
password if the password server is down.  An appropriate error message
will be printed, advising the caller to try again later.  Once the
password server acknowledges receipt the users new password, it should not
take too link for the information to propagate to the entire set of
\fBAuthentication Servers\fR\&.
.PP
\fBcpasswd\fR supports the following option:
.TP
\fB-h\fR
Tells \fBcpasswd\fR which
\fIhost\fR to bind to. This should be the
SCM.
.TP
\fB[username][@realm]\fR
Coda user name and the realm of the user whose password you
want to change. If the username is not specified, clog tries to
use the local login name. If the Coda realm name is not specified
clog falls back to using the default realm name as specified in
the venus.conf configuration file.
.SH "SEE ALSO"
.PP
\fBclog\fR(1)
.SH "AUTHOR"
.PP
.TP 0.2i
\(bu
1987, Adapted from AFS-2
.TP 0.2i
\(bu
Maria R. Ebling, 1990, Created man page
