.TH "CODA_REPLAY" "1" "25 April 2005" "Coda Distributed File System" ""

.SH NAME
coda_replay \- Manual reintegration tool
.SH SYNOPSIS

\fBcoda_replay\fR [ \fB\fIkey\fB\fR ] \fB\fIfilename\fB\fR

.SH "DESCRIPTION"
.PP
\fBcoda_replay\fR is a tool for manually reintegrating
operations done at a disconnected client.  It provides a superset of the
functionality of the tape-archive program, tar(1).  The
\fBkey\fR argument is a string of characters containing exactly
one function letter and possibly one or more function modifiers.  The
\fIfilename\fR argument specifies the tar/replay
format file containing the operations to be replayed.
.PP
The function portion of the key is specified by one of the following
letters:
.TP
\fBr\fR
Replay all operations specified in the file.
.TP
\fBs\fR
Strip out non-tar operations from the file and replay only
the tar operations.
.TP
\fBt\fR
Do not replay but simply list the operations specified in
the file.
.PP
The following characters may be used in addition to the letter which
selects the function desired:
.TP
\fBv\fR
Be verbose about the operations.
.TP
\fBh\fR
Be harsh in replay, i.e., abort the program if any replayed
operation fails.
.PP
\fBcoda_replay\fR can handle normal tar files since it
invokes tar to perform \fBcreate\fR,
\fBlink\fR, and \fBsymlink\fR operations.
However, its main purpose is to replay checkpoint files saved by the Coda
cache manager, Venus, during disconnected operation. These files may
contain operations unknown to tar: \fBsetattr\fR,
\fBunlink\fR, \fBrename\fR,
\fBmkdir\fR, and \fBrmdir\fR\&.
These other operations are encoded in the tar file by overloading the
linkflag and linkname fields. Consult the replay.h header file for more
details.
.SH "BUGS"
.PP
.TP 0.2i
\(bu
There is a limit of 100 characters imposed on filename
length by tar.
.TP 0.2i
\(bu
Filenames in checkpoint files generated by Venus are all
relative to the enclosing volume root.
.SH "SEE ALSO"
.PP
\fBtar\fR(1),
\fBtar\fR(5),
\fBvenus\fR(8)
.SH "AUTHORS"
.PP
.TP 0.2i
\(bu
Jay Kistler, 1990, Created
