subdir('scripts')
subdir('kerndep')
subdir('util')
subdir('vicedep')
subdir('dir')
subdir('al')
subdir('partition')
subdir('auth2')
subdir('vv')
subdir('lka')
subdir('vol')
subdir('librepair')
subdir('venus')
subdir('repair')
subdir('resolution')
subdir('volutil')
subdir('vtools')
subdir('vcodacon')
subdir('vice')
subdir('update')
subdir('asr')
subdir('egasr')
subdir('norton')
subdir('smon2')
subdir('asrlauncher')
