site_name: CodaFS Python module
repo_url: https://github.com/cmusatyalab/coda
repo_name: cmusatyalab/coda
theme:
  name: material
  features:
    - navigation.expand

extra:
  homepage: http://coda.cs.cmu.edu

copyright: Copyright 1995-2025 Carnegie Mellon University, Coda Group

plugins:
  - privacy
  - awesome-nav

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
