resolution_sources = [
  'compops.cc',
  'compops.h',
  'ops.cc',
  'ops.h',
  'parselog.cc',
  'parselog.h',
  'recle.cc',
  'recle.h',
  'recov_vollog.cc',
  'rename.cc',
  'resclient.cc',
  'rescomm.cc',
  'rescomm.h',
  'rescomm.private.h',
  'rescoord.cc',
  'rescoord.h',
  'resfile.cc',
  'resforce.cc',
  'resforce.h',
  'reslock.cc',
  'resolution.h',
  'resstats.cc',
  'resstats.h',
  'resutil.cc',
  'resutil.h',
  'rsle.cc',
  'rsle.h',
  'ruconflict.cc',
  'ruconflict.h',
  'rvmrescoord.cc',
  'rvmrestiming.h',
  'subpreres.cc',
  'subresphase2.cc',
  'subresphase3.cc',
  'subresphase34.cc',
  'timing.cc',
  'timing.h',
  'weres.cc',
]

resolution_lib = static_library('res',
  resolution_sources,
  build_by_default : false,
  include_directories : [
    config_h_include,
    base_inc,
    util_inc,
    vicedep_inc,
    dir_inc,
    kerndep_inc,
    al_inc,
    partition_inc,
    auth2_inc,
    vv_inc,
    lka_inc,
    vol_inc,
  ],
  dependencies : [rvm_rpc2_dep],
)

resolution_inc = include_directories('.')

resolution_dep = declare_dependency(
  include_directories : resolution_inc,
  link_with : resolution_lib,
)
