#!/bin/csh -f
#ifndef _BLURB_
#define _BLURB_
#/*
#
#            Coda: an Experimental Distributed File System
#                             Release 4.0
#
#          Copyright (c) 1987-1996 Carnegie Mellon University
#                         All Rights Reserved
#
#Permission  to  use, copy, modify and distribute this software and its
#documentation is hereby granted,  provided  that  both  the  copyright
#notice  and  this  permission  notice  appear  in  all  copies  of the
#software, derivative works or  modified  versions,  and  any  portions
#thereof, and that both notices appear in supporting documentation, and
#that credit is given to Carnegie Mellon University  in  all  documents
#and publicity pertaining to direct or indirect use of this code or its
#derivatives.
#
#CODA IS AN EXPERIMENTAL SOFTWARE SYSTEM AND IS  KNOWN  TO  HAVE  BUGS,
#SOME  OF  WHICH MAY HAVE SERIOUS CONSEQUENCES.  CARNEGIE MELLON ALLOWS
#FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION.   CARNEGIE  MELLON
#DISCLAIMS  ANY  LIABILITY  OF  ANY  KIND  FOR  ANY  DAMAGES WHATSOEVER
#RESULTING DIRECTLY OR INDIRECTLY FROM THE USE OF THIS SOFTWARE  OR  OF
#ANY DERIVATIVE WORK.
#
#Carnegie  Mellon  encourages  users  of  this  software  to return any
#improvements or extensions that  they  make,  and  to  grant  Carnegie
#Mellon the rights to redistribute these changes without encumbrance.
#*/
#
#static char *rcsid = "$Header: /coda/coda.cs.cmu.edu/project/coda/cvs/coda/coda-src/blurb/Attic/blurb-ansify,v 4.1 1997/01/08 21:49:28 rvb Exp $";
#endif /*_BLURB_*/


#ifndef _BLURB_
#define _BLURB_
#/*
#                           CODA FILE SYSTEM
#                             Release 2.0
#                      School of Computer Science
#                      Carnegie Mellon University
#                          Copyright 1987-94
#
#Coda  may  be  used  under license outside Carnegie Mellon University.
#Contact  the  Coda  Project   Coordinator   for   licensing   details.
#Unlicensed use or distribution of this code is illegal.
#*/
#
#
#static char *rcsid = "$Header: /coda/coda.cs.cmu.edu/project/coda/cvs/coda/coda-src/blurb/Attic/blurb-ansify,v 4.1 1997/01/08 21:49:28 rvb Exp $";
#endif /*_BLURB_*/


# Argument processing

set numfiles = $#argv

if ($numfiles == 0) then
    echo "Usage: blurb-ansify [files]"
    echo "       Filters each of [files] to convert non-ansi blurbs"
    echo "	 Saves old versions of files in filename.oldblurb"
endif

foreach file ($argv)
    if (! -r $file) then
	echo Could not find file $file, not ansifying
    else
	sed 's/endif \_BLURB\_/endif \/\*\_BLURB\_\*\//' < $file > $file.ansi
	mv $file $file.oldblurb
	mv $file.ansi $file
    endif
end
    
