#!/bin/csh -f
/* BLURB gpl

                           Coda File System
                              Release 5

          Copyright (c) 1987-1999 Carnegie Mellon University
                  Additional copyrights listed below

This  code  is  distributed "AS IS" without warranty of any kind under
the terms of the GNU General Public Licence Version 2, as shown in the
file  LICENSE.  The  technical and financial  contributors to Coda are
listed in the file CREDITS.

                        Additional copyrights
                           none currently

#*/


#ifndef _BLURB_
#define _BLURB_
#/*
#                           CODA FILE SYSTEM
#                             Release 2.0
#                      School of Computer Science
#                      Carnegie Mellon University
#                          Copyright 1987-94
#
#Coda  may  be  used  under license outside Carnegie Mellon University.
#Contact  the  Coda  Project   Coordinator   for   licensing   details.
#Unlicensed use or distribution of this code is illegal.
#*/
#
#
#static char *rcsid = "$Header: /coda/coda.cs.cmu.edu/project/coda/cvs/coda/coda-src/blurb/Attic/blurb-ansify,v 4.2 1998/12/21 22:25:19 jaharkes Exp $";
#endif /*_BLURB_*/


# Argument processing

set numfiles = $#argv

if ($numfiles == 0) then
    echo "Usage: blurb-ansify [files]"
    echo "       Filters each of [files] to convert non-ansi blurbs"
    echo "	 Saves old versions of files in filename.oldblurb"
endif

foreach file ($argv)
    if (! -r $file) then
	echo Could not find file $file, not ansifying
    else
	sed 's/endif \_BLURB\_/endif \/\*\_BLURB\_\*\//' < $file > $file.ansi
	mv $file $file.oldblurb
	mv $file.ansi $file
    endif
end
    
