#!/bin/csh

# This must be a CSH script so that the limit call can be used

switch (`uname`)
    case NetBSD:
	setenv PLATFORM i386_nbsd1
	setenv PATH /bin:/usr/bin
	exec /usr/bin/gmake ${argv[*]:q}
    breaksw
    case FreeBSD:
	setenv PLATFORM i386_fbsd2
	setenv PATH /bin:/usr/bin
	exec /usr/bin/gmake ${argv[*]:q}
    breaksw
    case Linux:
	setenv PLATFORM i386_linux2
	setenv PATH /bin:/usr/bin
	exec /usr/bin/make ${argv[*]:q}
    breaksw
    case Mach:
	setenv PLATFORM i386_mach
	setenv PATH /afs/cs/project/coda/@@sys/bin:/usr/cs/bin:/usr/ucb:/bin:/usr/bin
	setenv LPATH /afs/cs/project/coda/@@sys/lib:/usr/cs/lib:/lib:/usr/lib
	setenv CPATH /afs/cs/project/coda/@@sys/include:/usr/cs/include:/usr/include
	setenv GCC_EXEC_PREFIX /afs/cs/misc/gnu-comp/@sys/alpha/lib/gcc-lib/

	limit datasize unlimited
	exec /afs/cs/project/coda/@@sys/bin/gmake ${argv[*]:q}
   breaksw
endsw

