#!/bin/sh

# make the TAGS file for the Coda source.
rm TAGS
find . -type f -a \( -name '*.c' -or -name '*.lex' -or -name '*.yacc' -or -name '*.cc' -or -name '*.h' -or -name '*rpc2' \) | xargs etags -a
