#!/bin/sh

if [ x$1 != x ] ; then
  if [ ! -e $1 ]; then
    echo "Usage: printlocks [messagefile]"
    exit 1
  fi
fi

msg=$1
/bin/rm -f /tmp/rcslocks.out
touch /tmp/rcslocks.out

find . -name RCS -print | \
  while read dir 
    do
      if [ `uname` = "Mach" ] ; then
        rlog -L ${dir}/*,v | egrep 'locks: | *,v' 
      else
        rlog -L ${dir}/*,v | grep 'locked\|,v' | tee --append /tmp/rcslocks.out
      fi
    done

developers="bnoble braam bumba clement lily mre  raiff rvb satya tilt"

rm -f /tmp/printlocks.mail


for i in  $developers
do
  grep -B1 ${i} /tmp/rcslocks.out > /tmp/locks.$i
  if [   -s /tmp/locks.$i ]; then
    echo $i has locks

    if [ x$msg != x ]; then
      cat $msg /tmp/locks.$i | mail -s "Locks you hold" ${i}+@cs.cmu.edu
    fi
  else
    echo $i has no locks
  fi
done
