site_name: RVM Manual
repo_url: https://github.com/cmusatyalab/coda
repo_name: cmusatyalab/coda
theme:
  name: material

extra:
  homepage: http://coda.cs.cmu.edu

copyright: Copyright 1992-2026 Carnegie Mellon University, Coda Group

plugins:
  - search
  - privacy
  - awesome-nav
  - bibtex:
      bib_file: "docs/references.bib"

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

exclude_docs: |
  *.swp
